### ISSUE TITLE
What do the columns 3SS and 5SS mean in Vex-seq_positions.tsv?

### ISSUE THREAD

**Issue by yuanqm55** [scottiadamson/Vex-seq#1]
I try to get the exons related to the variants from Vex-seq_positions.tsv, however i was confused by the meaning of the column. Thanks!

**Comment by scottiadamson** [comment]
Hi, those are the positions relative the to 3' and 5' splice sites. As an example, if the 3SS column is -30, the variant is 30 bases upstream of the 3' splice site. If positive, it would be downstream of that splice site (i.e. 20 in the 5SS column would be downstream of the 5' splice site), and a positive value 3SS, but negative in 5SS are within the exon tested.

These values are the same ones to generate the plots "Figure_6_pt1_3primeSS_boxplot.png" and "Figure_6_pt2_5primeSS_boxplot.png" if helps makes things clearer.

I hope that helps. Let me know if you have any other questions.

**Comment by yuanqm55** [comment]
> Hi, those are the positions relative the to 3' and 5' splice sites. As an example, if the 3SS column is -30, the variant is 30 bases upstream of the 3' splice site. If positive, it would be downstream of that splice site (i.e. 20 in the 5SS column would be downstream of the 5' splice site), and a positive value 3SS, but negative in 5SS are within the exon tested.
> 
> These values are the same ones to generate the plots "Figure_6_pt1_3primeSS_boxplot.png" and "Figure_6_pt2_5primeSS_boxplot.png" if helps makes things clearer.
> 
> I hope that helps. Let me know if you have any other questions.

Hi, thanks for your reply, which really helps. However, based on what you said, when I try to get the target exon regins according to Vex-seq_positions.tsv, and then compare them to the Vex-seq data file provive by CAGI challenge (just for verification), most records match with 62 unmatched, which are all indels. For instence, chr1_114161136_AT_A, 3SS = -9, 5SS = -84, then the exon should be [114161145, 114161219], if I got it right. However, I can't find this exon in the annotation file for hg19, and the corresponding exon provided by CAGI is [114161154, 114161228].  I don't know where I've gone wrong. Thank you in advance!

**Comment by scottiadamson** [comment]
Hi,

You're right, it looks like there's something wrong with the "Vex-seq_positions.tsv" file for indels. The exon coordinates provided in the CAGI file should still be correct though. I'll post an updated file sometime soon.

Sorry for the confusion.

**Comment by scottiadamson** [comment]
So I looked into this further, and it seems like most of these are in homopolymer regions, so what's actually being reported in "Vex-seq_positions.tsv" is the index of the first difference in sequence between the variant and reference sequence. I realize that's kind of unclear so, I'll try to elaborate...

Below is the variant in your example: the deletion turns the sequence (the last T marks the beginning of the exon):
`reference: ATTTTTTTTGCCGTGGAGT`
`variant..: ATTTTTTT-GCCGTGGAGT`
even though the reference allele starts at -18, the variant position could really be marked anywhere between -17 and -10, because you could also denote other ways too and the observed sequence would be the same:
`variant..: A-TTTTTTTGCCGTGGAGT`
`variant..: ATTTT-TTTGCCGTGGAGT`

The way that these were marked is so that the first nucleotide of difference between the reference and variant sequence is reported from the 5' end of the RNA to the 3' end. There's still something off here because, by this logic, the position should actually be -10 because at the last T (index -10) in that homopolymer stretch is when the variant sequence that was tested is a G.

I wouldn't rely on the relative position for indels in homopolymer regions because it's kind of arbitrary where to put them. I think the only reason they are marked in the position that they are denoted is because of VCF file format conventions.

I hope that makes sense.

**Comment by yuanqm55** [comment]
Hi, I roughly understand what you mean. So, how can I get the exon coordinates for these indels with "Vex-seq_positions.tsv"? I'm working on a research project aiming to predict the variant effect on exon skipping using deep learning, and I want to evaluate my model using Vex-seq data. However, I don't want to quote the Vex-seq data on CAGI even though they directly provide the target exon coordinate for each variant, because I was heard that the data on CAGI are not public technically. Thank you very much!

**Comment by scottiadamson** [comment]
Your best bet is to parse it out of 68_97_final_sequences_fixed.tsv in the preprocess_data folder. It has the sequences that were used in the experiments, the variant information, as well as the coordinates of the exon that is associated with each variant.

**Comment by yuanqm55** [comment]
> Your best bet is to parse it out of 68_97_final_sequences_fixed.tsv in the preprocess_data folder. It has the sequences that were used in the experiments, the variant information, as well as the coordinates of the exon that is associated with each variant.

Hi, 68_97_final_sequences_fixed.tsv is really helpful to me! Thank you very much! By the way, do the columns "Upstream Int Adj" and "Down Int Adj" mean the upstream and downstream intron coordinates with respect to the target exon? I'm new to the field of genetic analysis. Thanks!

**Comment by scottiadamson** [comment]
> By the way, do the columns "Upstream Int Adj" and "Down Int Adj" mean the upstream and downstream intron coordinates with respect to the target exon?

Those fields are more specific to our experimental setup. Because of technological limitations, we are only able to test a limited amount of intronic sequence flanking the exon we are testing. Those are the genomic coordinates of the flanking intronic sequences that we use in our reporter system.
